on:
  push:
    branches: [main]
  pull_request:
name: Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.ArthurBrussee.Brush.flatpak
          manifest-path: brush_flatpak/org.ArthurBrussee.Brush.json
          cache-key: flatpak-builder-${{ github.sha }}
